"""add hash

Revision ID: f55dfd96336b
Revises: None
Create Date: 2016-03-20 13:55:32.577751

"""

# revision identifiers, used by Alembic.
revision = 'f55dfd96336b'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    ### end Alembic commands ###
